2024-05-28 19:34:46.484 [info] Test server listening.
2024-05-28 19:34:46.484 [info] > conda info --json
2024-05-28 19:34:46.510 [info] Found: /bin/python --> /usr/bin/python3.10
2024-05-28 19:34:46.530 [info] Found: /bin/python2 --> /bin/python2.7
2024-05-28 19:34:46.530 [info] Found: /bin/python2.7 --> /bin/python2.7
2024-05-28 19:34:46.547 [info] Found: /bin/python3 --> /bin/python3.10
2024-05-28 19:34:46.549 [info] Found: /bin/python3.10 --> /bin/python3.10
2024-05-28 19:34:46.576 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:46.576 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:46.793 [info] Found: /usr/bin/python --> /usr/bin/python3.10
2024-05-28 19:34:47.025 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:47.025 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:47.025 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:47.025 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:47.025 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:47.025 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-05-28 19:34:47.025 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-05-28 19:34:47.025 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-05-28 19:34:47.045 [info] Found: /usr/bin/python2 --> /usr/bin/python2.7
2024-05-28 19:34:47.046 [info] Found: /usr/bin/python2.7 --> /usr/bin/python2.7
2024-05-28 19:34:47.046 [info] Found: /usr/bin/python3 --> /usr/bin/python3.10
2024-05-28 19:34:47.047 [info] Found: /usr/bin/python3.10 --> /usr/bin/python3.10
2024-05-28 19:34:47.290 [info] > /bin/python -I /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py
2024-05-28 19:34:47.355 [info] > /bin/python2 -I /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py
2024-05-28 19:34:47.457 [info] > /bin/python3 -I /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py
2024-05-28 19:34:47.469 [warning] Error: Command failed: /bin/python2 -I /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/bin/python2 -I /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py'
}
2024-05-28 19:34:47.470 [error] Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
2024-05-28 19:34:47.528 [info] > /bin/python2 /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py
2024-05-28 19:34:47.635 [info] > /usr/bin/python2 -I /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py
2024-05-28 19:34:47.652 [warning] Error: Command failed: /usr/bin/python2 -I /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /usr/bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/usr/bin/python2 -I /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py'
}
2024-05-28 19:34:47.653 [error] Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
2024-05-28 19:34:47.709 [info] > /usr/bin/python2 /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/get_output_via_markers.py /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/pythonFiles/interpreterInfo.py
2024-05-28 19:34:47.842 [info] Python interpreter path: /bin/python
2024-05-28 19:34:48.029 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:48.029 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-05-28 19:34:53.746 [info] Starting Jedi language server for gayathriprasadkadiyala.
